<?php
$pageTitle = 'Receive Money';
$backUrl   = APP_URL . '/wallet/home';
$wid       = htmlspecialchars($walletUser['wallet_id']);
$qrData    = APP_URL . '/wallet/scan?wid=' . urlencode($walletUser['wallet_id']);
?>

<!-- qrcode.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>

<div style="padding-top:16px">

  <div class="receive-card">
    <div style="font-size:.75rem;color:#94a3b8;font-weight:600;margin-bottom:16px;text-transform:uppercase;letter-spacing:.5px">Your OrbitPesa Wallet ID</div>

    <!-- QR code (real, generated by qrcode.js) -->
    <div class="receive-qr" style="border:none;background:#fff;width:190px;height:190px;padding:6px;box-shadow:0 0 0 2px #e2e8f0">
      <div id="qrCanvas" style="width:178px;height:178px"></div>
    </div>

    <!-- Download button -->
    <div style="margin:10px 0 16px">
      <button onclick="downloadQR()" style="background:none;border:1px solid #cbd5e1;border-radius:10px;padding:7px 18px;font-size:.78rem;color:#475569;cursor:pointer;font-family:inherit">
        <i class="fas fa-download"></i> Download QR
      </button>
    </div>

    <div class="receive-id"><?= $wid ?></div>
    <div class="receive-id-label">Share your ID or QR to receive money instantly</div>

    <!-- Scan button -->
    <a href="<?= APP_URL ?>/wallet/scan" class="wbtn wbtn-primary" style="margin:14px 0 0;display:flex;align-items:center;justify-content:center;gap:8px;text-decoration:none">
      <i class="fas fa-qrcode"></i> Scan to Pay Someone
    </a>

    <button class="copy-btn" id="copyBtn" onclick="copyId()" style="margin-top:10px">
      <i class="fas fa-copy"></i> Copy Wallet ID
    </button>

    <div style="margin-top:24px;padding-top:20px;border-top:1px solid #f1f5f9">
      <div style="font-size:.75rem;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:.5px;margin-bottom:12px">Also share via</div>
      <div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap">
        <a href="https://wa.me/?text=<?= urlencode('Send me money on OrbitPesa Wallet. My wallet ID: ' . $walletUser['wallet_id']) ?>"
           target="_blank" class="copy-btn" style="text-decoration:none;color:#25d366;border-color:#25d366">
          <i class="fab fa-whatsapp"></i> WhatsApp
        </a>
        <a href="sms:?body=<?= urlencode('My OrbitPesa wallet ID: ' . $walletUser['wallet_id']) ?>"
           class="copy-btn" style="text-decoration:none;color:#3b82f6;border-color:#3b82f6">
          <i class="fas fa-sms"></i> SMS
        </a>
      </div>
    </div>
  </div>

  <div class="wform-card" style="margin-top:14px">
    <div style="font-size:.82rem;font-weight:700;color:#0f172a;margin-bottom:14px">How to receive money</div>
    <div style="display:flex;flex-direction:column;gap:12px">
      <div style="display:flex;gap:12px;align-items:flex-start">
        <div style="width:28px;height:28px;border-radius:50%;background:#dcfce7;color:#158347;display:flex;align-items:center;justify-content:center;font-size:.8rem;font-weight:800;flex-shrink:0">1</div>
        <div style="font-size:.82rem;color:#64748b">Share your QR code or Wallet ID <strong style="color:#0f172a"><?= $wid ?></strong></div>
      </div>
      <div style="display:flex;gap:12px;align-items:flex-start">
        <div style="width:28px;height:28px;border-radius:50%;background:#dcfce7;color:#158347;display:flex;align-items:center;justify-content:center;font-size:.8rem;font-weight:800;flex-shrink:0">2</div>
        <div style="font-size:.82rem;color:#64748b">The sender scans your QR or types your ID in their Send screen</div>
      </div>
      <div style="display:flex;gap:12px;align-items:flex-start">
        <div style="width:28px;height:28px;border-radius:50%;background:#dcfce7;color:#158347;display:flex;align-items:center;justify-content:center;font-size:.8rem;font-weight:800;flex-shrink:0">3</div>
        <div style="font-size:.82rem;color:#64748b">Money arrives instantly — <strong style="color:#158347">no fees</strong></div>
      </div>
    </div>
  </div>

</div>

<script>
const walletId  = '<?= addslashes($walletUser['wallet_id']) ?>';
const qrPayload = '<?= addslashes($qrData) ?>';

// Generate QR
const qr = new QRCode(document.getElementById('qrCanvas'), {
  text:           qrPayload,
  width:          178,
  height:         178,
  colorDark:      '#0D1B3E',
  colorLight:     '#ffffff',
  correctLevel:   QRCode.CorrectLevel.M,
});

function copyId() {
  const btn = document.getElementById('copyBtn');
  navigator.clipboard.writeText(walletId).then(() => {
    btn.innerHTML = '<i class="fas fa-check"></i> Copied!';
    btn.classList.add('copied');
    setTimeout(() => {
      btn.innerHTML = '<i class="fas fa-copy"></i> Copy Wallet ID';
      btn.classList.remove('copied');
    }, 2500);
  }).catch(() => {
    const ta = document.createElement('textarea');
    ta.value = walletId;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    btn.innerHTML = '<i class="fas fa-check"></i> Copied!';
    btn.classList.add('copied');
    setTimeout(() => {
      btn.innerHTML = '<i class="fas fa-copy"></i> Copy Wallet ID';
      btn.classList.remove('copied');
    }, 2500);
  });
}

function downloadQR() {
  // qrcode.js renders a canvas inside #qrCanvas
  const canvas = document.querySelector('#qrCanvas canvas');
  if (!canvas) return;
  const link   = document.createElement('a');
  link.download = 'orbitpesa-qr-' + walletId + '.png';
  link.href     = canvas.toDataURL('image/png');
  link.click();
}
</script>
